blank_issues_enabled: true
contact_links:
  - name: Support/Discussions
    url: https://github.com/dominicbytes/redotchestrator/discussions
    about: Ask questions, propose ideas, or discuss redotchestrator with the community.
