name: Security Scan
on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tagged release to check"
        required: true

jobs:
  scan_repository:
    name: Scan repository
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          submodules: recursive

      - name: Scan assets
        uses: hugoalh/scan-virus-ghaction@99c81e8991ad1074a14e5f22a21bce9be035e14e # v0.20.1
        with:
          found_summary: true
          statistics_summary: true

  scan_asset:
    name: Scan release assets
    runs-on: ubuntu-24.04
    # This only runs as part of workflow dispatch, otherwise only scan the repository
    if: ${{ github.event.inputs.tag != '' }}
    steps:

      - name: Download assets (Specific Tag)
        if: ${{ github.event.inputs.tag != '' }}
        uses: robinraju/release-downloader@28fc21f50d76778e7023361aa1f863e717d3d56f # v1.13
        with:
          tag: ${{ github.event.inputs.tag }}
          extract: true
          fileName: "redotchestrator*plugin.zip"

      - name: Scan assets
        uses: hugoalh/scan-virus-ghaction@99c81e8991ad1074a14e5f22a21bce9be035e14e # v0.20.1
        with:
          found_summary: true
          statistics_summary: true
